[package]
name = "condify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
im = "15.1.0"
imstr = "0.2.0"
itertools = "0.12.0"